version: '3.1'

services:
  nginx:
    image: nginx:alpine
    container_name: "hack-proxy"
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - frontend
      - application
  frontend:
    container_name: "hack-front"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 10001:80
    restart: always
  application:
    container_name: "hack-back"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    links:
      - mongo
    restart: always
  mongo:
    container_name: "hack-db"
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: hackathon
