version: '3.1'

services:
  frontend:
    container_name: "hack-front"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
  application:
    container_name: "hack-back"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:10000
    links:
      - mongo
    restart: always
  mongo:
    container_name: "hack-db"
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: hackathon
