@url=http://localhost:10000

### @name getConfiguration
GET {{url}}/config
Content-Type: application/json

### @name deleteConfiguration
DELETE {{url}}/config
Content-Type: application/json

### @name updateConfiguration
PUT {{url}}/config
Content-Type: application/json

{
  "instagram": {
    "auth": {
      "clientId": "34b24aa0326d47528d59253540f671d5",
      "clientSecret": "dbf6500c9f444faaa41fc05683912aef"
    }
  }
}


### @name grantAccessInstagram
GET {{url}}/instagram/grant?clientId=34b24aa0326d47528d59253540f671d5&clientSecret=dbf6500c9f444faaa41fc05683912aef
Content-Type: application/json
