
### @name fb
GET https://graph.facebook.com/ig_hashtag_search?user_id=101708527802345&q=zwift

###


387620128766053

a1a6be3c001f8920f875f6e057dd97af


387620128766053
  &access_token=EAAFgidgVOGUBAGT8VN1IxRHOpTP6BGgm3ZAAsmAYi3Ha3ssrTqwhmQvTCZB3XC9T5jUMG3BTaNiw5DGW1zFTSG8rqIvma7R0VvZCrKeYSIYSOgdN300zyCQicyTuKjtRLqOp9bJZAOMyZBZAaUIxUjnZBYNJzQPElmiDHniYMgTnHZAGB5HWkfMVy8m9NKzYZBbMZD
387620128766053|N18FvQepiyLqtdUH_6n0bmw9Kis
GET /ig_hashtag_search?user_id={user-id}&q={q}

###
GET https://graph.facebook.com/387620128766053
  ?user_id=387620128766053
  &access_token=387620128766053|N18FvQepiyLqtdUH_6n0bmw9Kis
  &q=zwift
####
GET https://graph.facebook.com/ig_hashtag_search
  ?user_id=387620128766053
  &access_token=387620128766053|N18FvQepiyLqtdUH_6n0bmw9Kis
  &q=zwift

#### @name getHashtag
GET https://graph.facebook.com/17843844418003850/recent_media
  ?user_id=17841406015491712
  &fields=id,media_type,comments_count,like_count
  &access_token=EAAFgidgVOGUBAGT8VN1IxRHOpTP6BGgm3ZAAsmAYi3Ha3ssrTqwhmQvTCZB3XC9T5jUMG3BTaNiw5DGW1zFTSG8rqIvma7R0VvZCrKeYSIYSOgdN300zyCQicyTuKjtRLqOp9bJZAOMyZBZAaUIxUjnZBYNJzQPElmiDHniYMgTnHZAGB5HWkfMVy8m9NKzYZBbMZD


### @name mediaID
GET https://graph.facebook.com/17872019914391984
  ?user_id=17841406015491712
  &fields=username
  &access_token=EAAFgidgVOGUBAGT8VN1IxRHOpTP6BGgm3ZAAsmAYi3Ha3ssrTqwhmQvTCZB3XC9T5jUMG3BTaNiw5DGW1zFTSG8rqIvma7R0VvZCrKeYSIYSOgdN300zyCQicyTuKjtRLqOp9bJZAOMyZBZAaUIxUjnZBYNJzQPElmiDHniYMgTnHZAGB5HWkfMVy8m9NKzYZBbMZD
  

###
GET https://graph.facebook.com/v3.3/321732548715156?fields=instagram_business_account&access_token=EAAFgidgVOGUBAGT8VN1IxRHOpTP6BGgm3ZAAsmAYi3Ha3ssrTqwhmQvTCZB3XC9T5jUMG3BTaNiw5DGW1zFTSG8rqIvma7R0VvZCrKeYSIYSOgdN300zyCQicyTuKjtRLqOp9bJZAOMyZBZAaUIxUjnZBYNJzQPElmiDHniYMgTnHZAGB5HWkfMVy8m9NKzYZBbMZD

###
GET https://graph.facebook.com/v3.3/321732548715156/media?access_token=EAAFgidgVOGUBAGT8VN1IxRHOpTP6BGgm3ZAAsmAYi3Ha3ssrTqwhmQvTCZB3XC9T5jUMG3BTaNiw5DGW1zFTSG8rqIvma7R0VvZCrKeYSIYSOgdN300zyCQicyTuKjtRLqOp9bJZAOMyZBZAaUIxUjnZBYNJzQPElmiDHniYMgTnHZAGB5HWkfMVy8m9NKzYZBbMZD

################
#### TWITER ####
################


# Consumer API keys
@twitterApiKey=egGPjeJGoxQkGggc7VT4w0DLE
@twitterApiSecretKey=UV78z8hTCMjBbMicBHGKfO0XCfTM1ZzFTx2UswhRgnIvWKRMQu

# Access token & access token secret
@twitterAccessToken=779513506576080896-IeBjEnKZ1Rz9cFnUOMUdtBYs7asBuTb
@twitterAccessTokenSecret=6rtpqk5K83Heq6bkTHMdpBk9WIV2kSriJ4MLd7WtK0Ylt

@twitterAuthCredetialBasic="ZWdHUGplSkdveFFrR2dnYzdWVDR3MERMRTpVVjc4ejhoVENNakJiTWljQkhHS2ZPMFhDZlRNMVp6RlR4MlVzd2hSZ25JdldLUk1RdQ==

@twitterHost=https://api.twitter.com
@twitterApiVersion=1.1
@twitterAPIUrl={{twitterHost}}/{{twitterApiVersion}}
### @name twitterAuth
POST {{twitterHost}}/oauth2/token
Authorization: Basic {{twitterAuthCredetialBasic}}
Content-Type: application/x-www-form-urlencoded;charset=UTF-8

grant_type=client_credentials

### @name twitterSearch
GET {{twitterAPIUrl}}/search/tweets.json?result_type=recent&q=%23zwift
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAL7p%2FAAAAAAAsucRrbleP%2BE53GIlCDuXBRjhjlo%3DkfnADF1BV5I3sHdwPXWLWdUdJUVLm9D376WzP4oCvF0FmosNkz

### Redo auth
# HTTP/1.1 401 Authorization Required
# connection: close
# content-encoding: gzip
# content-length: 87
# content-type: application/json; charset=utf-8
# date: Tue, 02 Jul 2019 11:06:49 GMT
# server: tsa_d
# strict-transport-security: max-age=631138519
# x-connection-hash: de1b27e52fa35e10c67aa7cd9b6703bd
# x-response-time: 135
# 
# {
#   "errors": [
#     {
#       "code": 89,
#       "message": "Invalid or expired token."
#     }
#   ]
# }