@url=http://localhost:8080

### @name getConfiguration
GET {{url}}/config
Content-Type: application/json

### @name deleteConfiguration
DELETE {{url}}/config
Content-Type: application/json

### @name updateConfiguration
PUT {{url}}/config
Content-Type: application/json

{
  "timer": {
    "maxDate": 129600000,
    "deadline": "2019-07-07T12:00:00.000Z"
  }
}

### @name getConfig
GET {{url}}/config